CREATE TABLE IF NOT EXISTS weekly_store_stats (
    week_start date NOT NULL,
    week_label text NOT NULL,
    side text NOT NULL DEFAULT 'All',
    day_type text NOT NULL DEFAULT 'all',
    total_net_sales real NOT NULL DEFAULT 0,
    total_gross_sales real NOT NULL DEFAULT 0,
    total_transactions integer NOT NULL DEFAULT 0,
    total_items real NOT NULL DEFAULT 0,
    trading_days integer NOT NULL DEFAULT 0,
    avg_daily_sales real NOT NULL DEFAULT 0,
    avg_transaction_value real NOT NULL DEFAULT 0,
    avg_daily_transactions real NOT NULL DEFAULT 0,
    member_transactions integer NOT NULL DEFAULT 0,
    member_net_sales real NOT NULL DEFAULT 0,
    non_member_transactions integer NOT NULL DEFAULT 0,
    non_member_net_sales real NOT NULL DEFAULT 0,
    member_sales_ratio real NOT NULL DEFAULT 0,
    member_tx_ratio real NOT NULL DEFAULT 0,
    unique_customers integer NOT NULL DEFAULT 0,
    total_labour_cost real DEFAULT NULL,
    labour_pct real DEFAULT NULL,
    cafe_labour_cost real DEFAULT NULL,
    retail_labour_cost real DEFAULT NULL,
    cafe_labour_pct real DEFAULT NULL,
    retail_labour_pct real DEFAULT NULL,
    adult_cafe_cost real DEFAULT NULL,
    adult_cafe_hours real DEFAULT NULL,
    adult_retail_cost real DEFAULT NULL,
    adult_retail_hours real DEFAULT NULL,
    teen_cafe_cost real DEFAULT NULL,
    teen_cafe_hours real DEFAULT NULL,
    teen_retail_cost real DEFAULT NULL,
    teen_retail_hours real DEFAULT NULL,
    weekday_labour_cost real DEFAULT NULL,
    saturday_labour_cost real DEFAULT NULL,
    sunday_labour_cost real DEFAULT NULL,
    public_holiday_labour_cost real DEFAULT NULL,
    weighted_margin_pct real DEFAULT NULL,
    cafe_margin_pct real DEFAULT NULL,
    retail_margin_pct real DEFAULT NULL,
    real_profit_pct real DEFAULT NULL,
    real_profit_dollars real DEFAULT NULL,
    unique_staff integer DEFAULT NULL,
    cafe_staff_count integer DEFAULT NULL,
    retail_staff_count integer DEFAULT NULL,
    total_hours real DEFAULT NULL,
    cafe_hours real DEFAULT NULL,
    retail_hours real DEFAULT NULL,
    teen_hours real DEFAULT NULL,
    adult_hours real DEFAULT NULL,
    revenue_per_hour real DEFAULT NULL,
    created_at timestamptz DEFAULT now(),
    PRIMARY KEY (week_start, side, day_type)
);

CREATE INDEX IF NOT EXISTS idx_wss_week ON weekly_store_stats (week_start);

ALTER TABLE weekly_store_stats ENABLE ROW LEVEL SECURITY;
CREATE POLICY "anon_read_wss" ON weekly_store_stats FOR SELECT TO anon USING (true);
